- name: Install linux-zen kernel for edge variant
  community.general.pacman:
    name:
      - linux-zen
      - linux-zen-headers
    state: present

- name: Remove default kernel modules
  shell:
    cmd: |
      current_kernel=$(uname -r)
      find /lib/modules /usr/lib/modules -mindepth 1 -maxdepth 1 -type d \
      ! -name "*zen*" -exec rm -rf {} + || true
