- name: Install NVIDIA dnf repository (negativo)
  shell:
    cmd: |
      dnf config-manager \
        --add-repo=https://negativo17.org/repos/epel-nvidia.repo


- name: Install NVIDIA dkms driver sources
  ansible.builtin.dnf:
    name:
      - nvidia-driver
      - dkms-nvidia
    state: present

- name: Configure dkms for NVIDIA open driver
  shell:
    cmd: |
      sed -i -e \
        's/kernel$/kernel-open/g' \
        /etc/nvidia/kernel.conf

- name: Build and install NVIDIA dkms drivers
  shell:
    cmd: |
      nvidia_version=$(dnf list installed | grep dkms-nvidia | awk '{print $2}' | cut -d':' -f2- | cut -d'-' -f1)
      kernel_version=$(dnf list installed kernel | awk '/kernel/{print $2}' | head -n1).x86_64
      dkms build -m nvidia/${nvidia_version} -k ${kernel_version} --force
      dkms install -m nvidia/${nvidia_version} -k ${kernel_version} --force
