- ansible.builtin.import_tasks: ../stage0/epel-repo.yaml

- ansible.builtin.import_tasks: ../stage0/dnf-config.yaml

- name: Install Development Tools
  ansible.builtin.dnf:
    name:
      - "@development"
      - distrobox
    state: present
