- ansible.builtin.import_tasks: ../stage1/gaming-hardware-compat.yaml

- ansible.builtin.import_tasks: ../stage1/nvidia-compat.yaml

- ansible.builtin.import_tasks: ../stage2/branding.yaml

- name: Rebuild initramfs
  shell:
    cmd: |
      kver=$(cd /usr/lib/modules && echo * | awk '{print $1}')
      dracut -vf /usr/lib/modules/$kver/initramfs.img $kver
