#!/usr/bin/env bash
#
# Adapted verbatim from ublue-os/aurora:
#   https://github.com/ublue-os/aurora/blob/main/system_files/shared/usr/bin/rechunker-group-fix
#
# Repairs /etc/gshadow after rebase from a legacy-rechunked image.
# Used by rechunker-group-fix.service; see that unit for full context and
# the list of upstream issues this works around.
#
# DO NOT REMOVE until every Razorfin image in the wild is built with the
# bazzite-style build-time passwd/group migration. Users WILL experience
# black screens and unbootable systems if this script malfunctions.

# To use this script, you'll want to put this in your systemd service:
# rm /etc/gshadow
# systemd-sysusers
# (run this script)
# systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev
# This will populate /etc/group successfully, and then populate /etc/gshadow
# with any missing groups that we nuked when we removed /etc/gshadow

GSHADOW_FILE="/etc/gshadow"
GROUP_FILE="/etc/group"

for f in $(cat $GROUP_FILE); do
   cut -f1 -d':' <(echo $f) | xargs -I{} grep ^"{}" $GSHADOW_FILE &>/dev/null || \
     echo $(cut -f1 -d':' <(echo $f)):'!*::' >> $GSHADOW_FILE
done
