- name: Install dnf config-manager
  ansible.builtin.dnf:
    name:
      - dnf-command(config-manager)
    state: present

- name: Exclude unwanted packages
  shell:
    cmd: |
      dnf config-manager --save \
        --setopt=exclude=PackageKit,PackageKit-command-not-found,rootfiles,firefox
