- name: Install SELinux Policy
  ansible.builtin.dnf:
    name:
      - selinux-policy
    state: present

- name: Patch Bootc update service to remove apply
  shell:
    cmd: |
      sed -i \
      's,ExecStart=/usr/bin/bootc update --apply --quiet,ExecStart=/usr/bin/bootc update --quiet,g' \
      /usr/lib/systemd/system/bootc-fetch-apply-updates.service

- name: Set /opt mutable
  shell:
    cmd: |
      mv /opt /var/opt
      ln -s /var/opt /opt

- name: Set /usr/ports mutable
  shell:
    cmd: |
      mv /usr/ports /var/usrports
      ln -s /var/usrports /usr/ports
