[[remotes]]
name = "flathub"
url = "https://dl.flathub.org/repo/flathub.flatpakrepo"

[[packages]]
bundle_url = "https://codeberg.org/HeliumOS/bootc-gtk/releases/download/0.2/org.heliumos.bootc_gtk.flatpak"

[[packages]]
remote = "flathub"
app_id = "org.gnome.Epiphany"
