- name: Install Gaming Hardware udev rules
  ansible.builtin.dnf:
    name:
      - steam-devices
    state: present

- name: Install NVIDIA Drivers
  ansible.builtin.dnf:
    name:
      - kmod-nvidia-open
      - nvidia-open-kmod
    state: present

- name: Rebuild initramfs
  shell:
    cmd: |
      kver=$(cd /usr/lib/modules && echo * | awk '{print $1}')
      dracut -vf /usr/lib/modules/$kver/initramfs.img $kver
