- name: Install Zsh
  ansible.builtin.dnf:
    name:
      - zsh
    state: present

- name: Set default shell to Zsh
  ansible.builtin.replace:
    path: /etc/default/useradd
    regexp: "bash"
    replace: "zsh"

- name: Set default Zsh config
  ansible.builtin.copy:
    content: |
      autoload -Uz compinit promptinit
      compinit
      promptinit

      PROMPT='%F{green}%n%f@%F{magenta}%m%f %F{blue}%B%~%b%f %# '
    dest: /etc/skel/.zshrc
