- name: Branding
  ansible.builtin.script: /workdir/files/branding.sh

- name: Configure SDDM theme
  shell:
    cmd: |
      sed -i \
        's,#Current=01-breeze-fedora,Current=breeze,g' \
        /etc/sddm.conf

      sed -i \
        's,/usr/share/wallpapers/Next/contents/images/5120x2880.png,/usr/share/wallpapers/Andromeda/contents/images/5338x5905.jpg,g' \
        /usr/share/sddm/themes/breeze/theme.conf

- name: Install Plymouth theme
  ansible.builtin.dnf:
    name:
      - plymouth-theme-spinner
    state: present

- name: Add EULA directories
  ansible.builtin.file:
    path: /usr/share/{{ item.vendor }}-release
    state: directory
  loop:
    - { vendor: razorfinos }
    - { vendor: almalinux }
    - { vendor: redhat }

- name: Add EULA files
  ansible.builtin.copy:
    content: |
      RazorfinOS 1 EULA

      RazorfinOS 1 comes with no guarantees or warranties of any sorts,
      either written or implied.

      The Distribution is released as GPLv2. Individual packages in the
      distribution come with their own licences. A copy of the GPLv2 license
      is included with the distribution media.
    dest: /usr/share/{{ item.vendor }}-release/EULA
  loop:
    - { vendor: razorfinos }
    - { vendor: almalinux }
    - { vendor: redhat }

- name: Create Plasma favorites defaults script for RazorfinOS
  ansible.builtin.copy:
    content: |
      #!/usr/bin/env bash

      set -eoux pipefail

      old_favorites=$(sqlite3 ~/.local/share/kactivitymanagerd/resources/database "SELECT targettedResource FROM 'ResourceLink';")
 
      for fav in $old_favorites; do
        qdbus-qt6 org.kde.ActivityManager /ActivityManager/Resources/Linking \
          org.kde.ActivityManager.ResourcesLinking.UnlinkResourceFromActivity \
          "org.kde.plasma.favorites.applications" \
          "applications:$fav" \
          ":global"
      done

      new_favorites="preferred://browser,org.kde.kontact.desktop,systemsettings.desktop,org.kde.dolphin.desktop,org.kde.kwrite.desktop,org.kde.konsole.desktop,org.kde.discover.desktop"
 
      echo "$new_favorites" | tr ',' '\n' | while read -r fav; do
        qdbus-qt6 org.kde.ActivityManager /ActivityManager/Resources/Linking \
          org.kde.ActivityManager.ResourcesLinking.LinkResourceToActivity \
          "org.kde.plasma.favorites.applications" \
          "applications:$fav" \
          ":global"
      done
    dest: /usr/bin/razorfinos-plasma-favorites-set-defaults
    mode: '0755'

- name: Install sqlite
  ansible.builtin.dnf:
    name:
      - sqlite
    state: present

- name: Create Plasma favorites defaults service for RazorfinOS
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Set default Plasma favorites service for RazorfinOS
      ConditionPathExists=!%s/.local/state/razorfinos-plasma-favorites-set-defaults
      Requires=plasma-kactivitymanagerd.service
      After=plasma-workspace.target

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/bash -c '/usr/bin/razorfinos-plasma-favorites-set-defaults && touch $HOME/.local/state/razorfinos-plasma-favorites-set-defaults'
    dest: /usr/lib/systemd/user/razorfinos-plasma-favorites-set-defaults.service

- name: Enable Plasma favorites defaults service for razorfinos
  ansible.builtin.file:
    src: /usr/lib/systemd/user/razorfinos-plasma-favorites-set-defaults.service
    dest: /etc/systemd/user/plasma-workspace.target.wants/razorfinos-plasma-favorites-set-defaults.service
    state: link
