- name: Branding
  ansible.builtin.script: /workdir/files/branding.sh

- name: Add EULA directories
  ansible.builtin.file:
    path: /usr/share/{{ item.vendor }}-release
    state: directory
  loop:
    - { vendor: razorfinos }
    - { vendor: almalinux }
    - { vendor: redhat }

- name: Add EULA files
  ansible.builtin.copy:
    content: |
      RazorfinOS 1 EULA

      RazorfinOS 1 comes with no guarantees or warranties of any sorts,
      either written or implied.

      The Distribution is released as GPLv2. Individual packages in the
      distribution come with their own licences. A copy of the GPLv2 license
      is included with the distribution media.
    dest: /usr/share/{{ item.vendor }}-release/EULA
  loop:
    - { vendor: razorfinos }
    - { vendor: almalinux }
    - { vendor: redhat }
