- name: Install Fedora GPG Keys
  ansible.builtin.dnf:
    name:
      https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Everything/x86_64/os/Packages/f/fedora-gpg-keys-42-1.noarch.rpm
    disable_gpg_check: true

- name: Install KDE Plasma Desktop
  ansible.builtin.dnf:
    name:
      - "@kde-desktop-environment"
      - angelfish
      - kcalc
      - kolourpaint
      - okular
      - krdp
      - https://dl.fedoraproject.org/pub/fedora/linux/updates/42/Everything/x86_64/Packages/q/qt6-qtwayland-6.9.1-3.fc42.x86_64.rpm
    state: present

- name: Disable Plasma Discover KNS Backend
  ansible.builtin.file:
    path: /usr/lib64/qt6/plugins/discover/kns-backend.so
    state: absent

- name: Install KDE Games
  ansible.builtin.dnf:
    name:
      - kmines
      - ksnakeduel
      - ksudoku
      - kreversi
    state: present

- name: Remove Unwanted KDE Apps
  ansible.builtin.dnf:
    name:
      - krfb

- name: Enable SDDM
  ansible.builtin.systemd_service:
    name: sddm
    enabled: true

- name: Disable Cockpit
  ansible.builtin.systemd_service:
    name: cockpit.socket
    enabled: false