- name: Install KDE Plasma Desktop
  community.general.pacman:
    name:
      - plasma
      - kde-applications
      - qt6-location
      - angelfish
      - kcalc
      - kolourpaint
      - okular
      - krdp
    state: present

- name: Disable Plasma Discover KNS Backend
  ansible.builtin.file:
    path: /usr/lib64/qt6/plugins/discover/kns-backend.so
    state: absent

- name: Install KDE Games
  community.general.pacman:
    name:
      - kmines
      - ksnakeduel
      - ksudoku
      - kreversi
    state: present

- name: Install Kvantum
  community.general.pacman:
    name:
      - kvantum
    state: present

- name: Remove Unwanted KDE Apps
  community.general.pacman:
    name:
      - krfb
    state: absent

- name: Enable SDDM
  ansible.builtin.file:
    src: /usr/lib/systemd/system/sddm.service
    dest: /etc/systemd/system/display-manager.service
    state: link
  ignore_errors: true

- name: Disable Cockpit socket
  ansible.builtin.file:
    path: /etc/systemd/system/sockets.target.wants/cockpit.socket
    state: absent

- name: Create script for /usr/share/sddm/themes overlay
  ansible.builtin.copy:
    content: |
      #!/usr/bin/env bash
      umount \
        /usr/share/sddm/themes
      mkdir -p \
        /var/usr_share_sddm_themes
      mkdir -p \
        /var/usr_share_sddm_themes_work
      mount -t overlay overlay \
        -o lowerdir=/usr/share/sddm/themes,upperdir=/var/usr_share_sddm_themes,workdir=/var/usr_share_sddm_themes_work \
        /usr/share/sddm/themes
    dest: /usr/bin/razorfinos-usr-share-sddm-themes-overlay
    mode: "0755"

- name: Create service for /usr/share/sddm/themes overlay
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Setup /usr/share/sddm/themes overlay

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/bash -c '/usr/bin/razorfinos-usr-share-sddm-themes-overlay'
    dest: /usr/lib/systemd/system/razorfinos-usr-share-sddm-themes-overlay.service

- name: Enable service for /usr/share/sddm/themes overlay
  ansible.builtin.file:
    src: /usr/lib/systemd/system/razorfinos-usr-share-sddm-themes-overlay.service
    dest: /etc/systemd/system/multi-user.target.wants/razorfinos-usr-share-sddm-themes-overlay.service
    state: link
