- name: Install Zsh
  ansible.builtin.dnf:
    name:
      - zsh
    state: present

- name: Set default shell to Zsh
  ansible.builtin.replace:
    path: /etc/default/useradd
    regexp: "bash"
    replace: "zsh"

- name: Set default Zsh config
  ansible.builtin.copy:
    content: |
      autoload -Uz compinit promptinit up-line-or-beginning-search down-line-or-beginning-search

      promptinit
      compinit
      zle -N up-line-or-beginning-search
      zle -N down-line-or-beginning-search

      zstyle ':completion:*' menu select
      PROMPT='%F{green}%n%f@%F{magenta}%m%f %F{blue}%B%~%b%f %# '

      HISTFILE=~/.zsh_history
      HISTSIZE=99999
      SAVEHIST=$HISTSIZE

      setopt EXTENDED_HISTORY
      setopt HIST_EXPIRE_DUPS_FIRST
      setopt HIST_IGNORE_DUPS
      setopt INC_APPEND_HISTORY
      setopt SHARE_HISTORY
    dest: /etc/skel/.zshrc