- name: Disable atd service
  ansible.builtin.file:
    path: /etc/systemd/system/multi-user.target.wants/atd.service
    state: absent

- name: Disable rpm-ostree-countme service
  ansible.builtin.file:
    path: /etc/systemd/system/timers.target.wants/rpm-ostree-countme.timer
    state: absent

- name: Enable HeliumOS timedate-config service
  ansible.builtin.file:
    src: /usr/lib/systemd/system/timedate-config.service
    dest: /etc/systemd/system/multi-user.target.wants/timedate-config.service
    state: link
