name: Build iso

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'RazorfinOS version to build'
        required: true
        type: string
        default: '1'
      arch:
        description: 'CPU Architecture'
        required: true
        type: string
        default: 'x86_64'

jobs:
  build_iso:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            podman

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.registry_user || github.actor }}
          password: ${{ secrets.registry_pass || secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build ISO
        env:
          VERSION: ${{ inputs.version }}
          IS_CANARY: ${{ github.ref == 'refs/heads/dev' && true || false }}
          ARCH: ${{ inputs.arch }}
        run: |
          make iso VERSION=${VERSION} IS_CANARY=${IS_CANARY} ARCH=${ARCH}

      - name: Upload iso
        uses: actions/upload-artifact@v4
        with:
          path: out/RazorfinOS*.iso
          retention-days: 7
