name: Build and Push image

on:
  workflow_call:
    inputs:
      is_canary:
        description: "Whether this is a canary release"
        required: true
        type: boolean

jobs:
  build_and_push:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    strategy:
      matrix:
        version: [10]
        is_edge: [false, true]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            podman

      - name: Build image
        id: build
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          IS_EDGE: ${{ matrix.is_edge }}
          REGISTRY_IMAGE: ${{ vars.registry_image }}
          VERSION: ${{ matrix.version }}
        run: |
          make image VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE}
          export TAG=$(make echo-tag VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE})
          
          export IMAGE=$(make echo-image)

          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT
      
      - name: Run Rechunker
        id: rechunk
        uses: hhd-dev/rechunk@ded27feba22df48134eece2c66ba0fca1289ff40 # v1.2.3
        with:
          rechunk: "ghcr.io/hhd-dev/rechunk:v1.2.2"
          ref: ${{ steps.build.outputs.IMAGE }}:${{ steps.build.outputs.TAG }}
          skip_compression: true
          version: ${{ steps.build.outputs.TAG }}
          pretty: ${{ steps.build.outputs.TAG }}
          revision: ${{ github.sha }}

      - name: Login to registry
        env:
          REGISTRY_USER: ${{ secrets.registry_user }}
          REGISTRY_PASS: ${{ secrets.registry_pass }}
          REGISTRY: ${{ vars.registry }}
        run: |
          sudo podman login --username $REGISTRY_USER --password $REGISTRY_PASS $REGISTRY

      - name: Push to registry
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          IS_EDGE: ${{ matrix.is_edge }}
          VERSION: ${{ matrix.version }}
        run: |
          RECHUNKED_IMAGE=$(sudo podman pull ${{ steps.rechunk.outputs.ref }})

          sudo podman image tag ${RECHUNKED_IMAGE} ${{ steps.build.outputs.IMAGE }}:${{ steps.build.outputs.TAG }}

          make push VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE}

