name: Build and Push image

on:
  workflow_call:
    inputs:
      is_canary:
        description: "Whether this is a canary release"
        required: true
        type: boolean

jobs:
  build_and_push:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [1]
        is_edge: [false, true]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Maximize build space
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo podman system prune -a -f || true
          echo "Disk space after cleanup:"
          df -h

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            podman

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.registry_user || github.actor }}
          password: ${{ secrets.registry_pass || secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build image
        id: build
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          IS_EDGE: ${{ matrix.is_edge }}
          REGISTRY_IMAGE: ${{ vars.registry_image }}
          VERSION: ${{ matrix.version }}
        run: |
          make image VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE}
          export TAG=$(make echo-tag VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE})

          export IMAGE=$(make echo-image)

          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT

      - name: Push image to registry
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          IS_EDGE: ${{ matrix.is_edge }}
          VERSION: ${{ matrix.version }}
        run: |
          make push VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE}

      - name: Sign container image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "${COSIGN_PRIVATE_KEY}" > cosign.key
          cosign sign --key cosign.key --yes ${{ steps.build.outputs.IMAGE }}:${{ steps.build.outputs.TAG }}
          rm -f cosign.key

      - name: Cleanup after build
        if: always()
        run: |
          echo "Cleaning up container storage before next matrix run..."
          sudo podman system prune -a -f || true
          sudo rm -rf /home/runner/.local/share/containers/storage/overlay-layers/* 2>/dev/null || true

      - name: Check disk space
        if: always()
        run: |
          df -h
          echo "Container storage usage:"
          du -sh /home/runner/.local/share/containers/storage/* 2>/dev/null || echo "Storage dir not found"

