name: Build and Push image

on:
  workflow_call:
    inputs:
      is_canary:
        description: "Whether this is a canary release"
        required: true
        type: boolean

jobs:
  build_and_push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [10]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            podman

      - name: Build image
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          REGISTRY_IMAGE: ${{ vars.registry_image }}
          VERSION: ${{ matrix.version }}
        run: |
          if [[ ${IS_CANARY} == true ]]; then
            make image VERSION=${VERSION} VARIANT=canary
          else
            make image VERSION=${VERSION} VARIANT=stable
          fi

      - name: Login to registry
        env:
          REGISTRY_USER: ${{ secrets.registry_user }}
          REGISTRY_PASS: ${{ secrets.registry_pass }}
          REGISTRY: ${{ vars.registry }}
        run: |
          podman login --username $REGISTRY_USER --password $REGISTRY_PASS $REGISTRY

      - name: Push to registry
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          VERSION: ${{ matrix.version }}
        run: |
          if [[ ${IS_CANARY} == true ]]; then
            make push VERSION=${VERSION} VARIANT=canary
          else
            make push VERSION=${VERSION} VARIANT=stable
          fi

