name: Build and Push image

on:
  workflow_call:
    inputs:
      is_canary:
        description: "Whether this is a canary release"
        required: true
        type: boolean

jobs:
  build_and_push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [1]
        is_edge: [false, true]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            podman

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.registry_user || github.actor }}
          password: ${{ secrets.registry_pass || secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build image
        id: build
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          IS_EDGE: ${{ matrix.is_edge }}
          REGISTRY_IMAGE: ${{ vars.registry_image }}
          VERSION: ${{ matrix.version }}
        run: |
          make image VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE}
          export TAG=$(make echo-tag VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE})
          
          export IMAGE=$(make echo-image)

          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT
      
      - name: Run Rechunker
        id: rechunk
        uses: hhd-dev/rechunk@ded27feba22df48134eece2c66ba0fca1289ff40 # v1.2.3
        with:
          rechunk: "ghcr.io/hhd-dev/rechunk:v1.2.2"
          ref: ${{ steps.build.outputs.IMAGE }}:${{ steps.build.outputs.TAG }}
          skip_compression: true
          version: ${{ steps.build.outputs.TAG }}
          pretty: ${{ steps.build.outputs.TAG }}
          revision: ${{ github.sha }}

      - name: Push to registry
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          IS_EDGE: ${{ matrix.is_edge }}
          VERSION: ${{ matrix.version }}
        run: |
          RECHUNKED_IMAGE=$(sudo podman pull ${{ steps.rechunk.outputs.ref }})

          sudo podman image tag ${RECHUNKED_IMAGE} ${{ steps.build.outputs.IMAGE }}:${{ steps.build.outputs.TAG }}

          make push VERSION=${VERSION} IS_CANARY=${IS_CANARY} IS_EDGE=${IS_EDGE}

      - name: Sign container image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "${COSIGN_PRIVATE_KEY}" > cosign.key
          cosign sign --key cosign.key --yes ${{ steps.build.outputs.IMAGE }}:${{ steps.build.outputs.TAG }}
          rm -f cosign.key

