name: Build and Push image

on:
  workflow_call:
    inputs:
      is_canary:
        description: "Whether this is a canary release"
        required: true
        type: boolean

jobs:
   build_and_push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [9, 10]
        variant: ["", "edge"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            podman

      - name: Build image
        env:
          REGISTRY_IMAGE: ${{ vars.registry_image }}
          VERSION: ${{ matrix.version }}
          VARIANT: ${{ matrix.variant }}
        run: |
          if [[ $VARIANT == "" ]]; then
            export CONTAINERFILE=$VERSION/Containerfile
          else
            export CONTAINERFILE=$VERSION/Containerfile.$VARIANT
          fi
          podman build -t $REGISTRY_IMAGE -f $CONTAINERFILE .

      - name: Login to registry
        env:
          REGISTRY_IMAGE: ${{ vars.registry_image }}
          REGISTRY_USER: ${{ secrets.registry_user }}
          REGISTRY_PASS: ${{ secrets.registry_pass }}
          REGISTRY: ${{ vars.registry }}
        run: |
          podman login --username $REGISTRY_USER --password $REGISTRY_PASS $REGISTRY

      - name: Push to registry
        env:
          IS_CANARY: ${{ inputs.is_canary }}
          REGISTRY_IMAGE: ${{ vars.registry_image }}
          REGISTRY: ${{ vars.registry }}
          VERSION: ${{ matrix.version }}
          VARIANT: ${{ matrix.variant }}
        run: |
          if [[ $IS_CANARY = true ]]; then
            export VERSION=$VERSION-canary
          fi

          if [[ $VARIANT == "" ]]; then
            export TAG=$VERSION
          else
            export TAG=$VERSION-$VARIANT
          fi

          if [[ $TAG == "10" ]]; then
            # Only 10-edge works for EL10
            exit 0
          else

          podman push $REGISTRY_IMAGE docker://$REGISTRY/$REGISTRY_IMAGE:$TAG
