name: HeliumOS Stable Release
on:
  push:
    branches:
      - stable
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit
    with:
      is_canary: false

