name: HeliumOS Canary Release
on:
  push:
    branches:
      - dev

jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push.yaml
    if: github.ref == 'refs/heads/dev'
    secrets: inherit
    with:
      is_canary: true
