name: RazorfinOS Canary Release
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push.yaml
    if: github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      is_canary: true
